# Generated by Django 5.0.6 on 2024-06-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '__first__'),
        ('flightHistory', '0002_flighthistory_sold_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('seat_location', models.CharField(max_length=50)),
                ('purchase_order', models.CharField(max_length=20, unique=True)),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightHistory.flighthistory')),
                ('fk_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
