# Generated by Django 5.0.6 on 2024-05-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fligth', '__first__'),
        ('itinerary', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fligth_date', models.DateField()),
                ('ticket_class', models.CharField(max_length=50)),
                ('pourchase_date', models.DateField()),
                ('seat_location', models.CharField(max_length=50)),
                ('fk_fligth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fligth.fligth')),
                ('fk_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.itinerary')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
