# Generated by Django 5.0.6 on 2024-06-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightHistory', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_date',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flightHistory.flighthistory'),
            preserve_default=False,
        ),
    ]
