# Generated by Django 5.0.6 on 2024-05-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='pourchase_date',
            new_name='purchase_date',
        ),
    ]
