# Generated by Django 5.0.6 on 2024-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_location',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], default='third', max_length=7),
        ),
    ]
