# Generated by Django 5.0.6 on 2024-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_seat_location_alter_ticket_ticket_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fk_date',
            new_name='fk_flight_history',
        ),
        migrations.AddField(
            model_name='ticket',
            name='buy_total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
