# Generated by Django 5.0.6 on 2024-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_fk_date_ticket_fk_flight_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
