# Generated by Django 5.0.6 on 2024-06-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_buy_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buy_total_price',
            field=models.FloatField(),
        ),
    ]
