# Generated by Django 5.0.6 on 2024-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_seat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_location',
            field=models.CharField(max_length=5),
        ),
    ]
