# Generated by Django 5.0.6 on 2024-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_seat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_location',
            field=models.CharField(),
        ),
    ]
