# Generated by Django 5.0.6 on 2024-05-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fk_plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.plane')),
            ],
        ),
    ]
