# Generated by Django 5.0.6 on 2024-06-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightHistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighthistory',
            name='sold_ticket',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
