# Generated by Django 5.0.6 on 2024-07-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightHistory', '0003_flighthistory_fk_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighthistory',
            name='sold_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
