# Generated by Django 5.0.6 on 2024-05-29 22:46

import apps.user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_onetimepassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.manager.CustomUserManager()),
            ],
        ),
    ]
