# Generated by Django 5.0.6 on 2024-06-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flightHistory', '0002_flighthistory_sold_ticket'),
        ('route', '0003_alter_route_fk_airport_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('stopover', models.BooleanField()),
                ('departure_time', models.TimeField()),
                ('fk_flight_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightHistory.flighthistory')),
                ('fk_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
