# Generated by Django 5.0.6 on 2024-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='fk_flight_history',
        ),
        migrations.AlterField(
            model_name='flight',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
