# Generated by Django 5.0.6 on 2024-06-08 01:58

import apps.flight.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_flight_fk_flight_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[apps.flight.validators.validate_code]),
        ),
    ]
