# Generated by Django 5.0.6 on 2024-05-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='fk_airport_arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='route.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='fk_airport_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='route.route'),
        ),
    ]
