# Generated by Django 5.0.6 on 2024-05-19 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fligthHistory', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fligth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('stopover', models.BooleanField()),
                ('departure_time', models.TimeField()),
                ('fk_flight_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fligthHistory.fligthhistory')),
                ('fk_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
